---
- hosts: all
  remote_user: root
  gather_facts: no
  
## Copy data from remote source to all hosts:

  tasks:
    - name: ensure the directory exists
      file:
        path: /tmp/centri
        state: directory
        
    - name: Using Ansible copy module for copying directory 
      copy:
        src: /scratch/centri                      
        remote_src: true                          
        dest: /tmp/                               
        local_follow: no
#       follow: no
        mode: 0755                                
        force: yes                                

    - name: Recursively change ownership of a directory
      file:
        path: /tmp/centri
        recurse: yes
        owner: root
        group: users
        mode: '0777'
  
