- hosts: all
  gather_facts: no
  become: true
  become_user: root
  tasks:
  
  - name: Remove a line from the file
    lineinfile:
      path: /etc/sudoers
      state: absent
      backup: yes
      validate: /usr/sbin/visudo -csf %s
      regexp: "{{ item }} "
    loop:
      - "^rssansbl"
      - "^nrpe"
      - "^%admins"     
