- hosts: all
  become: true
  become_user: root
  tasks:
  
  - name: replace line in file
    replace:
      path: /etc/sudoers
      regexp: 'includedir /etc/sudoers.d'
      replace: '#includedir /etc/sudoers.d'
      backup: yes
     
#  - name: Remove a line from the file
#    lineinfile:
#      path: /etc/sudoers
#      state: absent
#      backup: yes
#      validate: /usr/sbin/visudo -csf %s
#      regexp: "{{ item }} "
#    loop:
#      - "^rssansbl"
#      - "^nrpe"
#      - "^%admins"     
