- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Remove a line from the file
    lineinfile:
      path: /etc/sudoers
      state: absent
      validate: 'visudo -cf %s'
      backup: yes
      line: "{{ item }} "
    loop:
      - "rssansbl"
      - "^nrpe"
      - "^%admins"
