- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Remove a line from the file
    lineinfile:
      path: /etc/sudoers
      state: absent
      backup: yes
      regexp: " {{ item.regexp }}
    with_items:
      - { regexp: '^rssansbl ALL=(ALL) NOPASSWD: ALL' }
      - { regexp: '^nrpe ALL=(ALL) NOPASSWD: ALL' }
      - { regexp: '^%admins ALL=(ALL) NOPASSWD: ALL' }
         
