- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Remove a line from the file
    lineinfile:
      path: /etc/sudoers
      state: absent
      backup: yes
      validate: 'visudo -cf %s'
      regexp: "{{ item }} "
    loop:
      - "^rssansbl"
      - "^nrpe"
      - "^%admins"
  
# - name: replace a comment in sudoer file
#    replace:
#     path: /etc/sudoers
#      regexp: '
