- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Make sure this group is not in the sudoers configuration
    lineinfile:
      path: /etc/sudoers
      state: absent
      regexp: '^chachacha ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
