- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Make sure group wheel is not in the sudoers configuration
    lineinfile:
      path: /etc/sudoers
      state: absent
      regexp: 'XxX'
      line: 'chachacha ALL=(ALL) NOPASSWD: ALL'
      insertafter: EOF
      validate: 'visudo -cf %s'
