- hosts: all
  gather_facts: no
  become: true
  become_user: root
  tasks:
  
  - name: touche a file if doesn't exist
    file:
      path: /etc/sudoers.d/rpbseqit
      state: touch
      mode: '1440'
      modification_time: preserve
      access_time: preserve
            
  
  - name: create a file using content
#    copy:
#      content: '# This file was moved to /etc/other.conf'
#      dest: /etc/mine.conf
    blockinfile:
      path: /etc/sudoers.d/rpbseqit
      block: |
        %RPBseqit_team ALL=(ALL) NOPASSWD:ALL
        nrpe ALL=(ALL) NOPASSWD:ALL
        rssansbl ALL=(ALL) NOPASSWD:ALL
      
